export const ACTIONS = {
    ADD_USER: 'ADD_USER',
    READ_USER: 'READ_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    ACTIVE_RESULTS: 'ACTIVE_RESULTS',
    READ_USERS:'READ_USERS'
}